name: QA

on:
  # This workflow runs on pushes to the main branch.
  push:
    branches: [ main ]
  # This workflow runs on pull requests targeting the main branch.
  pull_request:
    branches: [ main ]

env:
  PHP_VERSION: 8.4

permissions:
  contents: read

jobs:

# ---------------------------------------------------------------------------------------

  qa:

# ---------------------------------------------------------------------------------------

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5 # https://github.com/actions/checkout
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2 # https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
          tools: none

      - name: Lint PHP files
        run: find . -name "*.php" -not -path "./vendor/*" | xargs -n1 -P4 php -l

      - name: Validate composer.json
        run: composer validate --no-ansi --strict composer.json

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Validate Coding Standards using php-cs-fixer
        run: ./vendor/bin/php-cs-fixer check --config ./build-tools/php-cs-fixer/php-cs-fixer.dist.php --show-progress=dots --using-cache=no --verbose

      - name: Run PHPStan static analysis
        run: |
          cd ./build-tools/.phpstan
          composer install --no-progress --prefer-dist
          cd ../../
          ./build-tools/.phpstan/vendor/bin/phpstan analyse -c ./build-tools/phpstan/phpstan.neon.dist --no-progress --error-format=github

      - name: Run Psalm static analysis
        run: |
          ./vendor/bin/psalm -c ./build-tools/psalm/psalm.xml --show-info=true

# ---------------------------------------------------------------------------------------

  tests-with-coverage:

# ---------------------------------------------------------------------------------------


    runs-on: ubuntu-latest
    needs: qa

    steps:
      - name: Checkout
        uses: actions/checkout@v5 # https://github.com/actions/checkout
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2 # https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: xdebug
          tools: none

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run test and generate code coverage report
        run: |
          ./vendor/bin/phpunit --config ./build-tools/phpunit/phpunit.coverage.xml --coverage-html build/coverage

      - name: Upload coverage to Pages artifact
        uses: actions/upload-pages-artifact@v4 # https://github.com/actions/upload-pages-artifact/
        with:
          name: coverage
          path: ./build/coverage

      #- name: Upload code coverage report
      #  uses: codecov/codecov-action@v5
      #  with:
      #    file: ./coverage.xml
