name: QA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PHP_VERSION: 8.4

permissions:
  contents: read

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
          tools: none

      - name: Lint PHP files
        run: find . -name "*.php" -not -path "./vendor/*" | xargs -n1 -P4 php -l

      - name: Validate composer.json
        run: composer validate --no-ansi --strict composer.json

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Validate Coding Standards using php-cs-fixer
        run: ./vendor/bin/php-cs-fixer check --config ./build-tools/php-cs-fixer/php-cs-fixer.dist.php --show-progress=dots --using-cache=no --verbose

      - name: Run PHPStan static analysis
        run: |
          cd ./build-tools/.phpstan
          composer install --no-progress --prefer-dist
          cd ../../
          ./build-tools/.phpstan/vendor/bin/phpstan analyse -c ./build-tools/phpstan/phpstan.neon.dist --no-progress --error-format=github

      #- name: Run test with code coverage report generation
      #  run: ./vendor/bin/phpunit --coverage-clover=coverage.xml

      #- name: Upload code coverage report
      #  uses: codecov/codecov-action@v3
      #  with:
      #    file: ./coverage.xml
